Repository Sylius/PriceHistoryPlugin, pull requests merged in 2023-03, with the labels that each got.

#54 [Shop] Fix updating lowest price information when selecting different variants/options from the list
  config/events.yaml
  config/services/providers.xml
  features/product/viewing_products/seeing_the_corresponding_lowest_price_before_the_discount_when_selecting_different_product_option.feature
  features/product/viewing_products/seeing_the_corresponding_lowest_price_before_the_discount_when_selecting_different_product_variant.feature
  phpstan.neon.dist
  public/app.js
  spec/Infrastructure/Provider/ProductVariantsPricesProviderSpec.php
  src/Infrastructure/Provider/ProductVariantsPricesProvider.php
  templates/Shop/Product/Show/_addToCart.html.twig
  templates/Shop/Product/Show/_inventory.html.twig
  templates/Shop/Product/Show/_javascripts.html.twig
  templates/Shop/Product/Show/_price.html.twig
  templates/Shop/Product/Show/_variantSelection.html.twig
  templates/Shop/Product/Show/_variants.html.twig
  tests/Behat/Context/Setup/ProductContext.php
  tests/Behat/Element/Shop/Product/ShowPage/LowestPriceInformationElement.php
  tests/Behat/Resources/services/contexts/setup.xml
  tests/Behat/Resources/suites/ui/product/viewing_products.yaml
Labels: UX/UI

#50 Reprocess lowest prices in a period when the period changes on channel
  config/services/listeners.xml
  features/product/viewing_products/seeing_correct_lowest_prices_when_period_changes_on_the_channel.feature
  spec/Infrastructure/EntityObserver/CreateLogEntryOnPriceChangeObserverSpec.php
  spec/Infrastructure/EntityObserver/ProcessLowestPriceOnCheckingPeriodChangeObserverSpec.php
  spec/Infrastructure/EventListener/ChannelPricingChangeListenerSpec.php
  spec/Infrastructure/EventListener/OnFlushEntityObserverListenerSpec.php
  src/DependencyInjection/Configuration.php
  src/DependencyInjection/SyliusPriceHistoryExtension.php
  src/Infrastructure/EntityObserver/CreateLogEntryOnPriceChangeObserver.php
  src/Infrastructure/EntityObserver/EntityObserverInterface.php
  src/Infrastructure/EntityObserver/ProcessLowestPriceOnCheckingPeriodChangeObserver.php
  src/Infrastructure/EventListener/ChannelPricingChangeListener.php
  src/Infrastructure/EventListener/OnFlushEntityObserverListener.php
  tests/Behat/Context/Setup/ChannelContext.php
  tests/Behat/Resources/suites/api/channel/managing_channels.yaml
  tests/Unit/DependencyInjection/ConfigurationTest.php
  tests/Unit/DependencyInjection/SyliusPriceHistoryExtensionTest.php
Labels: API, Feature

#58 [Shop] Minor UI fixes
  templates/Shop/Product/Show/_price.html.twig
  translations/messages+intl-icu.en.yaml
  translations/messages.en.yaml
Labels: UX/UI

#56 Populate the sylius_price_history_channel_pricing_log_entry table with initial data
  phpstan.neon.dist
  src/Infrastructure/Migrations/Version20230126131430.php
Labels: Feature

#55 Installation guide
  README.md
  traditional-installation-guide.md
Labels: Maintenance

#57 [API][Channel] Manage taxons excluded from showing lowest price
  config/serialization/Channel.xml
  config/services/serializers.xml
  features/channel/managing_channels/excluding_chosen_taxons_from_showing_the_lowest_price_of_discounted_products.feature
  psalm.xml
  spec/Infrastructure/Serializer/ChannelExcludedTaxonsDenormalizerSpec.php
  src/Infrastructure/Serializer/ChannelExcludedTaxonsDenormalizer.php
  tests/Api/Admin/ChannelTest.php
  tests/Api/DataFixtures/ORM/taxonomy.yaml
  tests/Api/Responses/admin/1.11/post_channel_with_taxons_excluded_from_showing_lowest_price_response.json
  tests/Api/Responses/admin/1.11/put_channel_with_taxons_excluded_from_showing_lowest_price_response.json
  tests/Api/Responses/admin/1.12/post_channel_with_taxons_excluded_from_showing_lowest_price_response.json
  tests/Api/Responses/admin/1.12/put_channel_with_taxons_excluded_from_showing_lowest_price_response.json
  tests/Behat/Context/Api/Admin/ManagingChannelsContext.php
  tests/Behat/Context/Setup/ChannelContext.php
  tests/Behat/Resources/services/contexts/api.xml
Labels: API, Feature

#60 [UI][Product] Improvements to displaying the lowest price before the discount
  config/admin_routing.yaml
  templates/Admin/Product/Show/_simpleProduct.html.twig
  templates/Admin/Product/Show/_variantContentPricing.html.twig
  templates/Admin/Product/show.html.twig
  traditional-installation-guide.md
  translations/messages.en.yaml
Labels: UX/UI

#59 [Behat][Maintenance] Slight contexts' cleanup
  tests/Behat/Context/Api/Admin/ManagingChannelsContext.php
  tests/Behat/Context/Setup/ChannelContext.php
  tests/Behat/Context/Transform/TaxonContext.php
  tests/Behat/Resources/services/contexts/api.xml
  tests/Behat/Resources/services/contexts/transform.xml
  tests/Behat/Resources/suites/api/channel/managing_channels.yaml
Labels: Behat, Maintenance

#66 Make the organisation of the templates more consistent
  config/events.yaml
  templates/Admin/Channel/Form/_additionalConfiguration.html.twig
  templates/Admin/Channel/Form/theme.html.twig
Labels: DX

#67 [Behat] Remove articles from feature names to simplify them
  features/channel/managing_channels/adding_channel_with_set_period_of_showing_lowest_price.feature
  features/channel/managing_channels/adding_channel_with_toggle_for_lowest_price.feature
  features/channel/managing_channels/editing_channel_with_set_period_of_showing_lowest_price.feature
  features/channel/managing_channels/editing_channel_with_toggle_for_lowest_price.feature
  features/channel/managing_channels/excluding_chosen_taxons_from_showing_lowest_price_of_discounted_products.feature
  features/product/viewing_product_in_admin_panel/viewing_lowest_price_before_discount_for_simple_product.feature
  features/product/viewing_product_in_admin_panel/viewing_lowest_price_before_discount_within_variant.feature
  features/product/viewing_products/seeing_correct_lowest_prices_when_period_changes_on_channel.feature
  features/product/viewing_products/seeing_corresponding_lowest_price_before_discount_when_selecting_different_product_option.feature
  features/product/viewing_products/seeing_corresponding_lowest_price_before_discount_when_selecting_different_product_variant.feature
  features/product/viewing_products/seeing_products_lowest_price_before_discount.feature
Labels: Behat, DX

#68 [UI] Fix label styles when the promotion is applied on any other variant than main one
  public/app.js
Labels: Bug, UX/UI

#64 [CI] Add PostgreSQL build
  .github/workflows/build.yml
  features/product/viewing_products/seeing_corresponding_lowest_price_before_discount_when_selecting_different_product_option.feature
  tests/Application/config/packages/doctrine.yaml
Labels: Maintenance

#62 [UI] Add autocomplete for exluding specific taxons from showing the lowest price
  config/services/forms.xml
  features/channel/managing_channels/excluding_chosen_taxons_from_showing_lowest_price_of_discounted_products.feature
  psalm.xml
  spec/Infrastructure/Serializer/ChannelExcludedTaxonsDenormalizerSpec.php
  src/Domain/Model/ChannelInterface.php
  src/Domain/Model/LowestPriceForDiscountedProductsAwareTrait.php
  src/Infrastructure/Form/Extension/ChannelTypeExtension.php
  src/Infrastructure/Serializer/ChannelExcludedTaxonsDenormalizer.php
  templates/Admin/Channel/Form/_additionalConfiguration.html.twig
  templates/Shop/Product/Show/_price.html.twig
  tests/Behat/Context/Api/Admin/ManagingChannelsContext.php
  tests/Behat/Context/Setup/ChannelContext.php
  tests/Behat/Context/Ui/Admin/ManagingChannelsContext.php
  tests/Behat/Element/Admin/Channel/ExcludeTaxonsFromShowingLowestPriceInputElement.php
  tests/Behat/Element/Admin/Channel/ExcludeTaxonsFromShowingLowestPriceInputElementInterface.php
  tests/Behat/Resources/services/contexts/ui.xml
  tests/Behat/Resources/services/elements/admin.xml
  tests/Behat/Resources/suites/ui/channel/managing_channels.yaml
  tests/Behat/Service/AutocompleteHelper.php
  translations/messages+intl-icu.en.yaml
  translations/messages.en.yaml
Labels: Feature, UX/UI

#71 [Migration] Fix column name
  src/Domain/Model/LowestPriceBeforeDiscountAwareTrait.php
  src/Infrastructure/Migrations/Version20230206081319.php
Labels: Bug

#70 [Documentation] Move legacy installation guide to docs directory
  README.md
  docs/legacy-installation-guide.md
Labels: Documentation, Maintenance

#73 Check if the product is assigned to any of the excluded taxons instead of all of them
  features/product/viewing_products/not_seeing_lowest_price_for_product_that_has_all_taxons_excluded_on_channel.feature
  features/product/viewing_products/not_seeing_lowest_price_for_product_that_has_taxon_excluded_on_channel.feature
  spec/Application/Checker/ProductVariantLowestPriceDisplayCheckerSpec.php
  src/Application/Checker/ProductVariantLowestPriceDisplayChecker.php
Labels: Enhancement

#74 [Behat] Reorganize scenarios in directories and suites
  behat.yml.dist
  features/product/viewing_price_history/accessing_price_history_from_configurable_product.feature
  features/product/viewing_price_history/accessing_price_history_from_simple_product.feature
  features/product/viewing_price_history/seeing_price_history_after_creating_product_variant.feature
  features/product/viewing_price_history/seeing_price_history_after_editing_product_variant.feature
  features/product/viewing_price_history/seeing_price_history_of_product_variant_after_changes_to_catalog_promotions.feature
  features/product/viewing_price_history/seeing_price_history_of_simple_product_after_changes_to_catalog_promotions.feature
  features/product/viewing_products_in_admin_panel/seeing_lowest_price_before_discount_for_simple_product.feature
  features/product/viewing_products_in_admin_panel/seeing_lowest_price_before_discount_within_variant.feature
  tests/Behat/Resources/suites.yaml
  tests/Behat/Resources/suites/api/product/viewing_price_history.yaml
  tests/Behat/Resources/suites/api/product/viewing_price_history_after_catalog_promotions.yaml
  tests/Behat/Resources/suites/domain/product/managing_price_history.yaml
  tests/Behat/Resources/suites/ui/product/accessing_price_history.yaml
  tests/Behat/Resources/suites/ui/product/viewing_price_history.yaml
  tests/Behat/Resources/suites/ui/product/viewing_price_history_after_catalog_promotions.yaml
Labels: Behat

#78 Unify lowest price naming
  spec/Application/Calculator/ProductVariantLowestPriceCalculatorSpec.php
  templates/Admin/Product/Show/_pricing.html.twig
  templates/Admin/Product/Show/_variantContentPricing.html.twig
  translations/messages.en.yaml
Labels: Enhancement

#77 [Maintenance] Adjust names to Sylius codebase
  config/admin_routing.yaml
  config/doctrine/ChannelPricingLogEntry.orm.xml
  config/grids/channel_pricing_log_entry.yaml
  spec/Infrastructure/Serializer/ChannelExcludedTaxonsDenormalizerSpec.php
  src/Domain/Model/LowestPriceForDiscountedProductsAwareTrait.php
  src/Infrastructure/Migrations/Version20230126131430.php
  src/Infrastructure/Migrations/Version20230222143342.php
  src/Infrastructure/Serializer/ChannelExcludedTaxonsDenormalizer.php
  templates/Admin/Product/Show/_pricing.html.twig
  templates/Admin/Product/Show/_variantContentPricing.html.twig
  tests/Behat/Resources/services/pages/price_history.xml
Labels: DX, Maintenance

#75 [BUG] Prevent calculating lowest price, when there is no discount
  features/product/viewing_products/seeing_corresponding_lowest_price_before_discount_when_selecting_different_product_variant.feature
  templates/Shop/Product/Show/_variants.html.twig
Labels: Bug

#69 Reprocess lowest prices asynchronously
  config/config.yaml
  config/services/command_dispatchers.xml
  config/services/command_handlers.xml
  config/services/listeners.xml
  spec/Application/CommandDispatcher/BatchedApplyLowestPriceOnChannelPricingsCommandDispatcherSpec.php
  spec/Application/CommandHandler/ApplyLowestPriceOnChannelPricingsHandlerSpec.php
  spec/Infrastructure/EntityObserver/ProcessLowestPriceOnCheckingPeriodChangeObserverSpec.php
  src/Application/Command/ApplyLowestPriceOnChannelPricings.php
  src/Application/CommandDispatcher/ApplyLowestPriceOnChannelPricingsCommandDispatcherInterface.php
  src/Application/CommandDispatcher/BatchedApplyLowestPriceOnChannelPricingsCommandDispatcher.php
  src/Application/CommandHandler/ApplyLowestPriceOnChannelPricingsHandler.php
  src/Infrastructure/EntityObserver/ProcessLowestPriceOnCheckingPeriodChangeObserver.php
Labels: Enhancement

#80 [Maintenance] Unify translations
  public/app.js
  spec/Infrastructure/Provider/ProductVariantsPricesProviderSpec.php
  src/Infrastructure/Provider/ProductVariantsPricesProvider.php
  templates/Shop/Product/Show/_price.html.twig
  templates/Shop/Product/Show/_variants.html.twig
  tests/Behat/Element/Shop/Product/ShowPage/LowestPriceInformationElement.php
  translations/messages+intl-icu.en.yaml
Labels: Maintenance

#81 Fix resource configuration in installation guides
  README.md
  docs/legacy-installation-guide.md
Labels: Documentation, Maintenance

#82 [Docs] Add info about running messenger consumer to the installation guide
  README.md
Labels: Maintenance

#84 Fix price history config annotations mapping
  ecs.php
  src/Domain/Model/ChannelPriceHistoryConfigAwareTrait.php
Labels: Bug

#83 [Documentation] Update legacy installation guide with current trait and messenger config
  docs/legacy-installation-guide.md
Labels: Documentation, Maintenance

#85 [Maintenance] Cover no price history config in display checker
  spec/Application/Checker/ProductVariantLowestPriceDisplayCheckerSpec.php
  src/Application/Checker/ProductVariantLowestPriceDisplayChecker.php
  tests/Api/DataFixtures/ORM/product_variant_with_no_prices.yaml
  tests/Api/DataFixtures/ORM/product_variant_without_discount.yaml
Labels: Maintenance

#86 [Maintenance] Overall cleanup
  config/events.yaml
  config/services.xml
  config/services/forms.xml
  config/services/listeners.xml
  config/services/serializers.xml
  config/validation/ChannelPriceHistoryConfig.xml
  src/Infrastructure/Form/Type/ChannelPriceHistoryConfigType.php
  templates/Admin/Channel/Form/_priceHistoryConfig.html.twig
  translations/messages.en.yaml
  translations/validators.en.yaml
Labels: DX, Maintenance
