Repository Sylius/PriceHistoryPlugin, pull requests merged in 2023-02, with the labels that each got.

#8 [Behat] Product's lowest price from 30 days before the discount
  features/product/viewing_products/viewing_a_products_lowest_price_from_30_days_before_the_discount.feature
Labels: Feature

#11 [DX] Minor style fixes
  tests/Behat/Context/Api/Admin/ManagingProductVariantsContext.php
  tests/Utils/ShopUserLoginTrait.php
Labels: DX, Enhancement

#13 [Behat] Minor scenarios and suites improvements
  features/product/managing_catalog_promotions/seeing_price_history_of_product_variant_after_changes_to_catalog_promotions.feature
  features/product/managing_catalog_promotions/seeing_price_history_of_simple_product_after_changes_to_catalog_promotions.feature
  tests/Behat/Resources/suites.yml
  tests/Behat/Resources/suites/api/product/viewing_products.yaml
  tests/Behat/Resources/suites/api/promotion/managing_catalog_promotions.yaml
Labels: Behat

#12 [Behat] Add additional scenarios for seeing lowest price on product show
  features/product/viewing_products/seeing_products_lowest_price_from_30_days_before_the_discount.feature
Labels: Behat, Feature

#17 Reorganize directory structure
  config/doctrine/ChannelPricingLogEntry.orm.xml
  config/serialization/ChannelPricingLogEntry.xml
  config/services/listeners.xml
  phpstan.neon.dist
  psalm.xml
  spec/Domain/Model/ChannelPricingLogEntrySpec.php
  spec/Infrastructure/EventListener/ChannelPricingChangeListenerSpec.php
  src/DependencyInjection/Configuration.php
  src/DependencyInjection/SyliusPriceHistoryExtension.php
  src/Domain/Model/ChannelPricingLogEntry.php
  src/Domain/Model/ChannelPricingLogEntryInterface.php
  src/Infrastructure/EventListener/ChannelPricingChangeListener.php
  src/Infrastructure/Migrations/Version20230126131430.php
  tests/Api/Admin/ChannelPricingLogEntryTest.php
Labels: DX, Maintenance

#21 Remove plugin suffix from configuration tree and services ids
  config/api_resources/ChannelPricingLogEntry.xml
  src/DependencyInjection/Configuration.php
  src/DependencyInjection/SyliusPriceHistoryExtension.php
  tests/Api/Admin/ChannelPricingLogEntryTest.php
  tests/Application/.env
Labels: Maintenance

#20 [API] Prepend configuration with API Platform mapping
  composer.json
  config/config.yaml
  src/DependencyInjection/SyliusPriceHistoryExtension.php
  tests/Application/config/packages/_sylius.yaml
  tests/Application/config/packages/api_platform.yaml
  tests/Unit/DependencyInjection/SyliusPriceHistoryExtensionTest.php
Labels: API, DX, Maintenance

#14 [Behat] Add scenarios for disabling showing the lowest price before the current discount
  features/channel/managing_channels/adding_channel_with_a_toggle_for_the_lowest_price.feature
  features/channel/managing_channels/editing_channel_with_a_toggle_for_the_lowest_price.feature
  features/product/viewing_products/seeing_products_lowest_price_from_30_days_before_the_discount.feature
Labels: Behat

#23 [DX] Refactor creating new channel pricing log entries
  config/services.xml
  config/services/listeners.xml
  phpstan.neon.dist
  psalm.xml
  spec/Application/Factory/ChannelPricingLogEntryFactorySpec.php
  spec/Application/Logger/PriceChangeLoggerSpec.php
  spec/Domain/Model/ChannelPricingLogEntrySpec.php
  spec/Infrastructure/EventListener/ChannelPricingChangeListenerSpec.php
  src/Application/Factory/ChannelPricingLogEntryFactory.php
  src/Application/Factory/ChannelPricingLogEntryFactoryInterface.php
  src/Application/Logger/PriceChangeLogger.php
  src/Application/Logger/PriceChangeLoggerInterface.php
  src/DependencyInjection/Configuration.php
  src/Domain/Model/ChannelPricingLogEntry.php
  src/Infrastructure/EventListener/ChannelPricingChangeListener.php
Labels: DX

#18 Clearing price history logs
  config/services.xml
  config/services/commands.xml
  features/product/managing_price_history/deleting_old_channel_pricing_entry_logs.feature
  phpstan.neon.dist
  phpunit.xml.dist
  psalm.xml
  spec/Infrastructure/Remover/ChannelPricingLogEntriesRemoverSpec.php
  src/Application/Remover/ChannelPricingLogEntriesRemoverInterface.php
  src/Domain/Repository/ChannelPricingLogEntryRepositoryInterface.php
  src/Infrastructure/Cli/Command/ClearPriceHistoryCommand.php
  src/Infrastructure/Doctrine/ORM/ChannelPricingLogEntryRepository.php
  src/Infrastructure/Doctrine/ORM/ChannelPricingLogEntryRepositoryInterface.php
  src/Infrastructure/Event/OldChannelPricingLogEntriesEvents.php
  src/Infrastructure/Remover/ChannelPricingLogEntriesRemover.php
  tests/Behat/Context/Domain/ManagingPriceHistoryContext.php
  tests/Behat/Context/Setup/PriceHistoryContext.php
  tests/Behat/Context/Setup/ProductContext.php
  tests/Behat/Resources/services/contexts/domain.xml
  tests/Behat/Resources/services/contexts/setup.xml
  tests/Behat/Resources/suites.yml
  tests/Behat/Resources/suites/domain/managing_price_history.yaml
  tests/Unit/Infrastructure/Cli/Command/ClearPriceHistoryCommandTest.php
Labels: Feature

#27 [DX] Include Behat files in the ECS config
  ecs.php
  tests/Behat/Context/Api/Admin/ChannelPricingLogEntryContext.php
  tests/Behat/Context/Api/Admin/ManagingChannelsContext.php
  tests/Behat/Context/Setup/CatalogPromotionContext.php
  tests/Behat/Context/Setup/ProductContext.php
  tests/Behat/Context/Ui/Admin/ChannelPricingLogEntryContext.php
  tests/Behat/Page/Admin/ChannelPricingLogEntry/IndexPage.php
  tests/Behat/Page/Admin/ChannelPricingLogEntry/IndexPageInterface.php
Labels: DX

#24 [Maintenance] Expose behat classes in autoload
  composer.json
Labels: Behat, DX, Maintenance

#28 Update LICENSE file
  LICENSE
Labels: Maintenance

#25 [UI] Add `Channel::lowestPriceForDiscountedProductsVisible`
  config/events.yaml
  config/services/forms.xml
  features/channel/managing_channels/adding_channel_with_a_toggle_for_the_lowest_price.feature
  features/channel/managing_channels/editing_channel_with_a_toggle_for_the_lowest_price.feature
  src/Infrastructure/Form/Extension/ChannelTypeExtension.php
  templates/Channel/Admin/Form/_additionalConfiguration.html.twig
  tests/Behat/Context/Api/Admin/ManagingChannelsContext.php
  tests/Behat/Context/Ui/Admin/ManagingChannelsContext.php
  tests/Behat/Element/Admin/Channel/LowestPriceFlagElement.php
  tests/Behat/Element/Admin/Channel/LowestPriceFlagElementInterface.php
  tests/Behat/Resources/services/contexts/ui.xml
  tests/Behat/Resources/services/elements/admin.xml
  tests/Behat/Resources/suites.yml
  tests/Behat/Resources/suites/ui/channel/managing_channels.yaml
  translations/messages.en.yaml
Labels: Feature

#31 [Behat] Scenarios of channel based lowest price for discounted products period
  features/channel/managing_channels/adding_channel_with_set_period_of_showing_the_lowest_price.feature
  features/channel/managing_channels/editing_channel_with_set_period_of_showing_the_lowest_price.feature
  features/product/viewing_products/seeing_correct_lowest_prices_when_period_changes_on_the_channel.feature
Labels: Behat, Feature

#26 Add missing show button for price history to simple product show page
  config/admin_routing.yaml
  config/events.yaml
  config/services.xml
  config/services/twig.xml
  features/product/accessing_price_history/accessing_price_history_from_configurable_product.feature
  features/product/accessing_price_history/accessing_price_history_from_simple_product.feature
  src/Application/Twig/SyliusVersionExtension.php
  templates/Admin/ChannelPricingLogEntry/Index/_breadcrumb.html.twig
  templates/Admin/Product/Show/_pricing.html.twig
  templates/Admin/Product/Show/_variantContentPricing.html.twig
  tests/Behat/Context/Ui/Admin/ProductShowPageContext.php
  tests/Behat/Element/Admin/Product/ShowPage/PricingElement.php
  tests/Behat/Element/Admin/Product/ShowPage/PricingElementInterface.php
  tests/Behat/Resources/services/contexts/ui.xml
  tests/Behat/Resources/services/elements/product.xml
  tests/Behat/Resources/suites.yml
  tests/Behat/Resources/suites/ui/product/accessing_price_history.yaml
Labels: Behat, UX/UI

#33 Add Scenario about exluding specific taxons from showing the lowest price of discounted products
  features/channel/managing_channels/excluding_chosen_taxons_from_showing_the_lowest_price_of_discounted_products.feature
  features/product/viewing_products/not_seeing_products_lowest_price_on_taxon_which_was_excluded.feature
Labels: Behat, Feature

#34 [Maintenance] Add arkitect
  .github/workflows/build.yml
  composer.json
  phparkitect.php
  spec/Domain/Model/ChannelPricingLogEntrySpec.php
  spec/Infrastructure/EventListener/ChannelPricingChangeListenerSpec.php
Labels: Maintenance

#37 [Maintenance] Remove composer.lock from test app
  .gitignore
  tests/Application/.gitignore
  tests/Application/composer.lock
Labels: Maintenance

#39 [UI] Add CheckingPeriod field to channel create and update page
  config/events.yaml
  features/channel/managing_channels/adding_channel_with_set_period_of_showing_the_lowest_price.feature
  features/channel/managing_channels/editing_channel_with_set_period_of_showing_the_lowest_price.feature
  src/Infrastructure/Form/Extension/ChannelTypeExtension.php
  templates/Channel/Admin/Form/_additionalConfiguration.html.twig
  templates/Channel/Admin/Form/theme.html.twig
  tests/Behat/Context/Ui/Admin/ManagingChannelsContext.php
  tests/Behat/Element/Admin/Channel/DiscountedProductsCheckingPeriodInputElement.php
  tests/Behat/Element/Admin/Channel/DiscountedProductsCheckingPeriodInputElementInterface.php
  tests/Behat/Page/Admin/Channel/UpdatePage.php
  tests/Behat/Resources/services/contexts/ui.xml
  tests/Behat/Resources/services/elements/admin.xml
  tests/Behat/Resources/services/pages/channel.xml
  tests/Behat/Resources/suites/ui/channel/managing_channels.yaml
  translations/messages.en.yaml
Labels: Feature, UX/UI

#43 [Maintenance] Adjust Messenger env variables
  tests/Application/.env
Labels: Maintenance

#41 [Channel] Add more validation
  config/services.xml
  config/services/listeners.xml
  config/validation/Channel.xml
  features/channel/managing_channels/adding_channel_with_set_period_of_showing_the_lowest_price.feature
  features/channel/managing_channels/editing_channel_with_set_period_of_showing_the_lowest_price.feature
  spec/Infrastructure/EventListener/BeforeDenormalizationChannelValidationListenerSpec.php
  src/Infrastructure/EventListener/BeforeDenormalizationChannelValidationListener.php
  tests/Api/Admin/ChannelTest.php
  tests/Behat/Context/Api/Admin/ManagingChannelsContext.php
  tests/Behat/Context/Ui/Admin/ManagingChannelsContext.php
  translations/validators.en.yaml
Labels: API, Enhancement

#42 Minor Fixes
  templates/Channel/Admin/Form/_additionalConfiguration.html.twig
  templates/Channel/Admin/Form/theme.html.twig
  tests/Behat/Resources/services/contexts/ui.xml
  tests/Behat/Resources/services/pages/channel.xml
Labels: Bug

#40 [UI] Show information about product's lowest price
  config/events.yaml
  features/product/viewing_products/seeing_products_lowest_price_before_the_discount.feature
  templates/Shop/Product/Show/_price.html.twig
  templates/Shop/Product/Show/_priceWidget.html.twig
  tests/Behat/Context/Ui/Shop/ProductContext.php
  tests/Behat/Element/Shop/Product/ShowPage/LowestPriceInformationElement.php
  tests/Behat/Element/Shop/Product/ShowPage/LowestPriceInformationElementInterface.php
  tests/Behat/Resources/services/contexts/ui.xml
  tests/Behat/Resources/services/elements/admin.xml
  tests/Behat/Resources/services/elements/shop.xml
  tests/Behat/Resources/suites.yml
  tests/Behat/Resources/suites/ui/product/viewing_products.yaml
  translations/messages.en.yaml
Labels: Feature, UX/UI

#47 [Channel] Add taxons excluded from showing lowest price
  ecs.php
  src/Domain/Model/ChannelInterface.php
  src/Domain/Model/LowestPriceForDiscountedProductsAwareTrait.php
  src/Domain/Model/LowestPriceForDiscountedProductsCheckingPeriodTrait.php
  src/Domain/Model/LowestPriceForDiscountedProductsVisibleAwareTrait.php
  src/Infrastructure/Migrations/Version20230222143342.php
  tests/Api/Responses/admin/1.11/post_channel_with_custom_lowest_price_for_discounted_products_checking_period_field_response.json
  tests/Api/Responses/admin/1.11/post_channel_with_default_lowest_price_for_discounted_products_checking_period_field_response.json
  tests/Api/Responses/admin/1.11/post_channel_with_disabled_lowest_price_for_discounted_products_visible_field_response.json
  tests/Api/Responses/admin/1.11/post_channel_with_enabled_lowest_price_for_discounted_products_visible_field_response.json
  tests/Api/Responses/admin/1.11/put_channel_with_custom_lowest_price_for_discounted_products_checking_period_field_response.json
  tests/Api/Responses/admin/1.11/put_channel_with_disabled_lowest_price_for_discounted_products_visible_field_response.json
  tests/Api/Responses/admin/1.11/put_channel_with_enabled_lowest_price_for_discounted_products_visible_field_response.json
  tests/Api/Responses/admin/1.11/put_channel_with_no_lowest_price_for_discounted_products_checking_period_field_response.json
  tests/Api/Responses/admin/1.11/put_channel_with_no_lowest_price_for_discounted_products_visible_field_response.json
  tests/Api/Responses/admin/1.12/post_channel_with_custom_lowest_price_for_discounted_products_checking_period_field_response.json
  tests/Api/Responses/admin/1.12/post_channel_with_default_lowest_price_for_discounted_products_checking_period_field_response.json
  tests/Api/Responses/admin/1.12/post_channel_with_disabled_lowest_price_for_discounted_products_visible_field_response.json
  tests/Api/Responses/admin/1.12/post_channel_with_enabled_lowest_price_for_discounted_products_visible_field_response.json
  tests/Api/Responses/admin/1.12/put_channel_with_custom_lowest_price_for_discounted_products_checking_period_field_response.json
  tests/Api/Responses/admin/1.12/put_channel_with_disabled_lowest_price_for_discounted_products_visible_field_response.json
  tests/Api/Responses/admin/1.12/put_channel_with_enabled_lowest_price_for_discounted_products_visible_field_response.json
  tests/Api/Responses/admin/1.12/put_channel_with_no_lowest_price_for_discounted_products_checking_period_field_response.json
  tests/Api/Responses/admin/1.12/put_channel_with_no_lowest_price_for_discounted_products_visible_field_response.json
  tests/Application/src/Entity/Channel.php
Labels: Feature

#48 [LowestPriceBeforeTheDiscount][API][Admin] Serialization of `lowestPriceBeforeDiscount` field
  config/api_resources/product_variant.yaml
  config/serialization/ChannelPricing.xml
  tests/Api/Admin/ProductVariantTest.php
  tests/Api/Responses/admin/product/get_product_variant_with_discount_in_home_channel_and_without_discount_in_fashion_channel_response.json
  tests/Api/Responses/admin/product/get_product_variant_with_no_prices.json
  tests/Api/Responses/admin/product/post_product_variant_with_lowest_price_before_discount_response.json
  tests/Api/Responses/admin/product/put_product_variant_with_lowest_price_before_discount_response.json
Labels: Feature

#49 [Maintenance] Minor architecture cleanup
  config/services/twig.xml
  psalm.xml
  spec/Application/Logger/PriceChangeLoggerSpec.php
  spec/Domain/Factory/ChannelPricingLogEntryFactorySpec.php
  src/Application/Logger/PriceChangeLogger.php
  src/DependencyInjection/Configuration.php
  src/Domain/Factory/ChannelPricingLogEntryFactory.php
  src/Domain/Factory/ChannelPricingLogEntryFactoryInterface.php
  src/Infrastructure/Twig/SyliusVersionExtension.php
Labels: DX, Maintenance

#46 [API][UI] Not seeing lowest price when its turned off on channel
  config/services.xml
  config/services/serializers.xml
  config/services/twig.xml
  features/product/viewing_products/seeing_products_lowest_price_before_the_discount.feature
  spec/Application/Calculator/ProductVariantLowestPriceCalculatorSpec.php
  spec/Application/Templating/Helper/PriceHelperSpec.php
  spec/Infrastructure/Serializer/ProductVariantNormalizerSpec.php
  src/Application/Calculator/ProductVariantLowestPriceCalculator.php
  src/Application/Calculator/ProductVariantLowestPriceCalculatorInterface.php
  src/Application/Templating/Helper/PriceHelper.php
  src/Infrastructure/Serializer/ProductVariantNormalizer.php
  src/Infrastructure/Twig/PriceExtension.php
  templates/Shop/Common/Macro/money.html.twig
  templates/Shop/Product/Show/_price.html.twig
Labels: API, Feature

#51 Fix adding product with only original price
  behat.yml.dist
  spec/Infrastructure/EventListener/ChannelPricingChangeListenerSpec.php
  src/Infrastructure/EventListener/ChannelPricingChangeListener.php
Labels: Bug

#53 Fix the lowest price on a product that has the lowest price set beyond the checking period but it is still the lowest price in this period
  features/product/viewing_products/seeing_products_lowest_price_before_the_discount.feature
  src/Domain/Repository/ChannelPricingLogEntryRepositoryInterface.php
  src/Infrastructure/Doctrine/ORM/ChannelPricingLogEntryRepository.php
  tests/Behat/Context/Setup/ProductContext.php
  tests/Behat/Resources/suites/api/product/viewing_products.yaml
  tests/Behat/Resources/suites/ui/product/viewing_products.yaml
Labels: Bug
