Repository Sylius/PriceHistoryPlugin, pull requests merged in 2023-01, with the labels that each got.

#2 Minor improvements
  .github/workflows/build.yml
  .gitignore
  tests/Application/.env
  tests/Application/webpack.config.js
Labels: Enhancement

#5 [Behat] Add scenarios for viewing the catalog price history of all variants of a product and of a simple product
  features/product/managing_product_variants/seeing_correct_catalog_price_history_after_creating_product_variant.feature
  features/product/managing_product_variants/seeing_correct_catalog_price_history_after_editing_product_variant.feature
  features/product/viewing_product_in_admin_panel/viewing_product_catalog_price_history_for_a_simple_product.feature
  features/product/viewing_product_in_admin_panel/viewing_product_catalog_price_history_within_product_variant.feature
  tests/Behat/Context/Setup/CatalogPromotionContext.php
  tests/Behat/Context/Setup/ProductContext.php
  tests/Behat/Resources/services.xml
  tests/Behat/Resources/services/contexts/setup.xml
Labels: Behat, Feature

#6 Add ChannelPricingLogEntry model
  .github/workflows/build.yml
  config/doctrine/ChannelPricingLogEntry.orm.xml
  phpstan.neon
  phpstan.neon.dist
  psalm.xml
  spec/Model/ChannelPricingLogEntrySpec.php
  src/DependencyInjection/Configuration.php
  src/DependencyInjection/SyliusPriceHistoryExtension.php
  src/Migrations/Version20230126131430.php
  src/Model/ChannelPricingLogEntry.php
  src/Model/ChannelPricingLogEntryInterface.php
Labels: Feature
